name: Deploy

on:
  push:
    branches:
    - main

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install
        run: go mod tidy
      - name: Build
        run: go build -v main.go
      - name: Zip
        run: zip -j deploy.zip main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Upload Zip
        run: aws lambda update-function-code --function-name lambda-deploy --zip-file fileb://deploy.zip
      