name: Deploy

on:
  push:
    branches:
    - main
    
permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        env:
          TEST_AWS_ROLE: ${{ secrets.AWS_ROLE }}
        run: |
          echo ${#TEST_AWS_ROLE}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install
        run: go mod tidy
      - name: Build
        run: go build -v main.go
      - name: Zip
        run: zip -j deploy.zip main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        secrets: inherit
        env:
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
      - name: Upload Zip
        run: aws lambda update-function-code --function-name lambda-deploy --zip-file fileb://deploy.zip
      
